site_name: 转工管群 Wiki
site_description: 转工管群群页面
site_url: https://smewin.github.io/
nav:
    - 主页: index.md
    - 简介: 
      - 工管院简介: sme_intro/intro.md
      - 贡献者指南: sme_intro/contributors.md
      - FAQ: sme_intro/FAQ.md
    - 人物志: 
      - 疾旋鼬: people/jxy.md
    - 金融工程:
      - 简介: fe/index.md
      - 财务会计与管理决策: fe/famd/index.md
      - 固定收益证券: fe/fis/index.md
      - 金融软件工程: fe/fse/index.md
      - 货币银行学: fe/mb/index.md
      - 经济学原理: fe/pe/index.md
    - 工业工程:
      - 简介: ie/index.md
      - 运筹学I: ie/or1/index.md
      - 运筹学II: ie/or2/index.md
      - 基础工业工程: ie/bie/index.md
      - 离散优化算法: ie/doa/index.md
      - 管理学: ie/man/index.md
      - 应用统计学: ie/as/index.md
    - 自动化:
      - 简介: auto/index.md
      - 自动化导论(SME): auto/aai/index.md
    - CS:
      - 简介: cs/cs.md
      - ICS: 
          - ICS: cs/ics/ics_pre.md
          - ICS_Cheat_Sheet: cs/ics/cheat_sheet.md
          - ICS_理论试题选解:
            - 第4章 程序的链接: cs/ics/theory/ICS-04/
            - 第6章 层次结构存储系统: cs/ics/theory/ICS-06/
            - 第7章 异常控制流: cs/ics/theory/ICS-07/
            - 第8章 I/O操作的实现: cs/ics/theory/ICS-08/
          - ICS_PA(x86): 
            - 在PA开始之前（x86）: cs/ics/ics_pa_pre.md
            - PA 1-1 世界诞生的前夜: cs/ics/pa/ics_pa-1-1.md
            - PA 1-2 不停运算的机器: cs/ics/pa/ics_pa-1-2.md
            - PA 1-3 浮点运算的大门: cs/ics/pa/ics_pa-1-3.md
            - PA 2-1 简单复杂的机器: cs/ics/pa/ics_pa-2-1.md
            - PA 2-2 Linux中的文件: cs/ics/pa/ics_pa-2-2.md
            - PA 2-3 字符串求值: cs/ics/pa/ics_pa-2-3.md
            - PA 3-1 更快访问的追求: cs/ics/pa/ics_pa-3-1.md
            - PA 3-2 虚实交错的魔法: cs/ics/pa/ics_pa-3-2.md
            - PA 3-3 超越容量的界限: cs/ics/pa/ics_pa-3-3.md
            - PA 4-1 来自外部的声音: cs/ics/pa/ics_pa-4-1.md
            - PA 4-2 冯诺依曼的构想: cs/ics/pa/ics_pa-4-2.md
            - PA 4-3 编写不朽的传奇: cs/ics/pa/ics_pa-4-3.md
      - ICS_RISCV:
        - 简介: cs/ics_riscv/index.md
        - 课程介绍: cs/ics_riscv/course_intro/index.md
        - 编写宗旨: cs/ics_riscv/guidelines/index.md
        - PA:
          - 编写内容介绍: cs/ics_riscv/PA/index.md
          - PA0：开始之前: cs/ics_riscv/PA/PA0_1.md
          - PA0：初识 Linux: cs/ics_riscv/PA/PA0_2.md
          - PA0：关于 Vim: cs/ics_riscv/PA/PA0_3.md
          - PA0：与 AI 交互: cs/ics_riscv/PA/PA0_4.md
          - PA1：准备工作: cs/ics_riscv/PA/PA1_1.md
          - PA1：对计算机的抽象: cs/ics_riscv/PA/PA1_2.md
          - PA1： NEMU 代码导读: cs/ics_riscv/PA/PA1_3.md
          - PA1：表达式求值：编译器与软件测试: cs/ics_riscv/PA/PA1_4.md
          - PA1：旅行伙伴加入： fuck'n fish: cs/ics_riscv/PA/PA1_5.md
        - PA+:
          - 简介: cs/ics_riscv/PA_plus/index.md
          - PA+1：表达式生成器: cs/ics_riscv/PA_plus/PA_plus1.md
        - PA现场赛:
          - 简介: cs/ics_riscv/competition/index.md
        - labs:
          - 编写内容介绍: cs/ics_riscv/labs/index.md
          - lab1：大整数运算: cs/ics_riscv/labs/lab1.md
        - 理论课: cs/ics_riscv/theory/index.md
      - 数据结构与算法: cs/dsa/dsa.md
      - 离散数学: cs/dm/index.md
      - 面向对象: cs/fop/index.md
    - 通修:
      - 简介: general/index.md
    - ISGSNSG:
      - 简介: sec/index.md

    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true


theme:
  name: material
  favicon: pic/logo.png  # 图标路径
  features:
    - navigation.tabs # 启用顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - git-revision-date-localized:
      type: datetime  # 完整日期时间格式
      time_format: "%Y年%m月%d日 %H:%M"  # 自定义中文时间格式
      timezone: Asia/Shanghai  # 设置时区
      locale: zh  # 设置中文显示
      show_if_no_revision: false  # 没有历史时不显示
